### ISSUE TITLE
Rotation Option

### ISSUE THREAD

**Issue by tjpeden** [ngokevin/aframe-layout-component#5]
Perhaps an option to set rotation as well? Might only be useful for circle, but maybe not.

**Comment by ngokevin** [comment]
You can just use the rotation component https://aframe.io/docs/0.3.0/components/rotation.html

**Comment by tjpeden** [comment]
I'm sorry, an option to have the component calculate the rotation so that the entities face the center of the circle for the circle layout.

**Comment by ngokevin** [comment]
You can combine it with the look-at component https://github.com/ngokevin/aframe-look-at-component

Most the layout examples do it like http://ngokevin.github.io/aframe-layout-component/dodecahedron/index.html

**Comment by tjpeden** [comment]
Oh good idea, I totally just looked at that like 5 minutes ago and it didn't even dawn on me! lol Thanks!

**Comment by tjpeden** [comment]
You have so many really awesome components!

**Comment by ngokevin** [comment]
no problem, it's not immediately obvious to incant these magical spells :)
